# Generated by Django 4.2.5 on 2023-09-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
    ]
