# Generated by Django 4.2.5 on 2023-09-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='media',
        ),
    ]
