# Generated by Django 4.2.5 on 2023-09-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal', '0002_alter_schedule_user'),
        ('blog', '0002_alter_feedback_user'),
        ('user', '0003_remove_user_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
